### ISSUE TITLE
Unable to build tentacle

### ISSUE THREAD

**Issue by rajcheval** [OctopusDeploy/Octopus-Docker#12]
I am trying to build the tentacle on Win 2016 with containers VM in Azure.

I run this command

docker build --tag octopusdeploy/tentacle-prerelease:3.15.8 --build-arg OctopusVersion=latest --file Tentacle\Dockerfile .

Here is the error:

Step 7/12 : ADD source/ /Installers
ADD failed: GetFileAttributesEx \\?\C:\Windows\TEMP\docker-builder619624613\source: The system cannot find the file specified.

I am running the build from a command window running as administrator.

let e know how I can resolve this issue.  Only reason I am building on my own its because there a fix that will allow me to use private IP for tentacle. The code for fix has been checked in but the image has not been published.

**Comment by matt-richardson** [comment]
If you want to build it, I'd recommend using the scripts, rather than a straight `docker build` command. Took a while to get the incantation correct.

That said, I've just re-published the Tentacle container image for `3.17.0` so that it's got the fix you're looking for.

I'll close this one - feel free to reopen if you're still facing an issue.
