### ISSUE TITLE
How are you servicing older container images?

### ISSUE THREAD

**Issue by christianacca** [OctopusDeploy/Octopus-Docker#48]
## Question (TL;DR)

What is the plan for servicing the existing images that are being published to docker hub? Specifically, what's the plan on keeping the OS patched in these images?

## Same question (long form)

You guys release updates to the product regularly. I understand that you have both a LTS "lane" and fast lane. I see that for each release on either lane you are cutting a new container image (at least for the octopus deploy server). 

But what about those images that are not at the "tip" of the release train? What's the plan on keeping the OS patched in these images?

**Comment by MJRichardson** [comment]
Hey @christianacca,
To be honest, we don't have a plan for updating the base image of older versions.
Our thinking is if you are on the LTS track, you should be able to feel confident in upgrading (which will pick up the latest base image).  

And as a fallback, customers can always create their own images.  
Though having said that, if we were asked I'm sure we would produce an image with the desired base.

BTW, for discussion topics (as opposed to technical issues), please feel welcome to jump into our [community Slack](https://octopus.com/slack), or our [support forum](https://help.octopus.com/).  Only because they tend to be better suited to a conversation, and you are likely to get a faster response.

I hope that helps!

**Comment by christianacca** [comment]
Thanks @MJRichardson for the confirmation of what I already suspected ;-)
