### ISSUE TITLE
Windows Server 1709 support

### ISSUE THREAD

**Issue by tesharp** [OctopusDeploy/Octopus-Docker#9]
Its not possible to use the server on Windows Server 1709. Would it be possible to create a container based on microsoft/windowsservercore:1709 image?

**Comment by matt-richardson** [comment]
Unfortunately, while we want to do this, it isn't something we're going to be able to tackle very soon.

I suspect when we do, we'll probably need to do something similar to https://stefanscherer.github.io/poc-build-images-for-1709-without-1709/, so we can build images for both 2016 and 1709. It'll probably be the start of the manifest work so that when octopus runs on Nano server (and eventually linux!), it'll be easy to extend.

I also suspect this is not the easiest bit of work to bite off, but if you're feeling adventurous, PRs are definitely welcome!

**Comment by nmajin** [comment]
Apparently there is just an issue with microsoft/windowsservercore:latest image, so what I am missing in terms of why you guys cannot just add a tag for 1709, which I can run a container fine on Windows Server Core 2016 (1709)?

**Comment by matt-richardson** [comment]
Unfortunately, its not as simple as adding a tag. It has to be rebuilt completely with a new base image, which implies building a whole new one on a Windows 1709 based server. 1709 images are not compatible with 2016 RTM and vice versa, as far as I know. If we do it the "proper" way, we'd have to spin up infrastructure to build the second instance type, and figure out the manifest so customers not yet on 1709 can still use it. If we want to build it without this infrastructure, we need to follow the approach above, and still sort out the manifest.

As mentioned above, while this is something we would like to do, this is not a high priority for us right now. However, we are definitely willing to accept PRs to help us get there.

In the meantime, everything you need to build your own image is available in this repo, so you are welcome to build your own.

**Comment by adhodgson1** [comment]
Now of course we have 1803 images to look after as well so it becomes very unwieldy! :(

**Comment by mcasperson** [comment]
1709 and 1803 images are now available through https://hub.docker.com/r/octopusdeploy/octopusdeploy/
